name: Set up dev env requirements
description: Set up dev env requirements for build and tests

runs:
  using: composite
  steps:
  - name: Setup dev env requirement 📦
    run: |
      cp -f requirements-dev.txt ../requirements-dev.txt
      cat ../.build/python/requirements-dev.txt >> ../requirements-dev.txt
    working-directory: ./docker-stacks
    shell: bash

  - name: Copy patchs 📦
    run: |
      cp -fr ../.build/python/okdp/patch/* ./
      cp -fr ../.build/python/okdp ./
    working-directory: ./docker-stacks
    shell: bash

