#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Patch create a build environment
description: Patch create a build environment ./docker-stacks/.github/actions/create-dev-env

# In order for ./docker-stacks/.github/actions/create-dev-env to work, 
# copy the requirements-dev.txt files into root project folder
runs:
  using: composite
  steps:
  - name: Patch create a build environment 📦
    run: |
      cp -f requirements-dev.txt ../requirements-dev.txt
      cat ../.build/python/requirements-dev.txt >> ../requirements-dev.txt
    working-directory: ./docker-stacks
    shell: bash


