# c.f. ./docker-stacks/.github/actions/create-dev-env
# Copied to skip Set Up Docker when running on nektos/act.
# Can be removed and use the original (./docker-stacks/.github/actions/create-dev-env) when the issue below resolved.
name: Build environment
description: Create a build environment

runs:
  using: composite
  steps:
    - name: Set Up Python 🐍
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Dev Dependencies 📦
      run: |
        pip install --upgrade pip
        pip install --upgrade -r requirements-dev.txt
      shell: bash

    # We need to have a recent docker version
    # More info: https://github.com/jupyter/docker-stacks/pull/2255
    # Can be removed after Docker Engine is updated
    # https://github.com/actions/runner-images/issues/11766
    - name: Set Up Docker 🐳
      if: env.ACT != 'true'
      uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
      with:
        set-host: true
        
