name: Build, test, and push jupyter datascience images

on:
  workflow_call:
    inputs:
      python_dev_tag:
        description: Tag to use for latest base images (foundation, minimal, etc)
        required: true
        type: string
      registry:
        description: The list of tags space separated values
        required: true
        type: string
      runs-on:
        description: GitHub Actions Runner image
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_token:
        required: true

defaults:
  run:
    working-directory: ./docker-stacks

jobs:
  r:
    uses: ./.github/workflows/docker-build-test-push-latest.yml
    with:
      parent-image: minimal-notebook:${{ inputs.python_dev_tag }}
      image: r-notebook:${{ inputs.python_dev_tag }}
      registry: ${{ inputs.registry }}
      runs-on: ${{ inputs.runs-on }}
    secrets:
      registry_username: ${{ secrets.registry_username }}
      registry_token: ${{ secrets.registry_token }}

  datascience:
    uses: ./.github/workflows/docker-build-test-push-latest.yml
    with:
      parent-image: scipy-notebook:${{ inputs.python_dev_tag }}
      image: datascience-notebook:${{ inputs.python_dev_tag }}
      registry: ${{ inputs.registry }}
      runs-on: ${{ inputs.runs-on }}
    secrets:
      registry_username: ${{ secrets.registry_username }}
      registry_token: ${{ secrets.registry_token }}

  # julia:
  #   uses: ./.github/workflows/docker-build-test-push-latest.yml
  #   with:
  #     parent-image: minimal-notebook:${{ inputs.python_dev_tag }}
  #     image: julia-notebook
  #     registry: ${{ inputs.registry }}
  #     runs-on: ${{ inputs.runs-on }}
  #   secrets:
  #     registry_username: ${{ secrets.registry_username }}
  #     registry_token: ${{ secrets.registry_token }}

  # tensorflow:
  #   uses: ./.github/workflows/docker-build-test-push-latest.yml
  #   with:
  #     parent-image: scipy-notebook:${{ inputs.python_dev_tag }}
  #     image: tensorflow-notebook
  #     registry: ${{ inputs.registry }}
  #     runs-on: ${{ inputs.runs-on }}
  #   secrets:
  #     registry_username: ${{ secrets.registry_username }}
  #     registry_token: ${{ secrets.registry_token }}

  # pytorch:
  #   uses: ./.github/workflows/docker-build-test-push-latest.yml
  #   with:
  #     parent-image: scipy-notebook:${{ inputs.python_dev_tag }}
  #     image: pytorch-notebook
  #     registry: ${{ inputs.registry }}
  #     runs-on: ${{ inputs.runs-on }}
  #   secrets:
  #     registry_username: ${{ secrets.registry_username }}
  #     registry_token: ${{ secrets.registry_token }}






