name: Jupyter pyspark build images template

on:
  workflow_call:
    inputs:
      python_version:
        description: Python version
        required: true
        type: string
      spark_download_url:
        description: Spark dist download url
        required: true
        type: string
      spark_version:
        description: Spark version
        required: true
        type: string
      java_version:
        description: Java version
        required: true
        type: string
      scala_version:
        description: Scala version
        required: true
        type: string
      hadoop_version:
        description: Hadoop version
        required: true
        type: string
      python_dev_tag:
        description: Tag to use for latest base images (foundation, minimal, etc)
        required: true
        type: string
      spark_dev_tag:
        description: Tag to use for latest pyspark images (pyspark, all-spark, etc)
        required: true
        type: string
      publish_to_registry:
        description: Wheter to push to the registry
        required: false
        type: string
        default: "false"
      registry:
        description: The list of tags space separated values
        required: false
        type: string
      git_latest_release_tag:
        description: The latest remote release tag 
        required: false
        type: string
        default: ""

jobs:
  pyspark:
    uses: ./.github/workflows/build-multi-arch-image-template.yml
    with:
      parent-image: scipy-notebook:${{ inputs.python_dev_tag }}
      image: pyspark-notebook:${{ inputs.spark_dev_tag }}
      registry: ${{ inputs.registry }}
      publish_to_registry: ${{ inputs.publish_to_registry }}
      git_latest_release_tag: ${{ inputs.git_latest_release_tag }}
      build-args:
        spark_download_url=${{ inputs.spark_download_url }}
        spark_version=${{ inputs.spark_version }}
        openjdk_version=${{ inputs.java_version }}
        scala_version=${{ inputs.scala_version }}
        hadoop_version=${{ inputs.hadoop_version }}
    secrets: inherit

  all-spark:
    uses: ./.github/workflows/build-multi-arch-image-template.yml
    with:
      parent-image: pyspark-notebook:${{ inputs.spark_dev_tag }}
      image: all-spark-notebook:${{ inputs.spark_dev_tag }}
      registry: ${{ inputs.registry }}
      publish_to_registry: ${{ inputs.publish_to_registry }}
      git_latest_release_tag: ${{ inputs.git_latest_release_tag }}
    secrets: inherit
    needs: [pyspark]

